export const DATA = [
    {
        id: 0,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Active',
    },
    {
        id: 1,
        image: require('../../assets/imgs/wallet.jpg'),
        title: 'Big Garden Salad',
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Top-Up',
        title: 'Top Up E-Wallet',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Cancelled',
    },
    {
        id: 2,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Active',
    },
    {
        id: 3,
        image: require('../../assets/imgs/wallet.jpg'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Top-Up',
        title: 'Top Up E-Wallet',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Completed',
    },
    {
        id: 4,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Cancelled',
    },
    {
        id: 5,
        image: require('../../assets/imgs/wallet.jpg'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Top-Up',
        title: 'Top Up E-Wallet',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Active',
    },
    {
        id: 6,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Completed',
    },
    {
        id: 7,
        image: require('../../assets/imgs/wallet.jpg'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Top-Up',
        title: 'Top Up E-Wallet',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Cancelled',

    },
    {
        id: 8,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Active',
    },
    {
        id: 9,
        image: require('../../assets/imgs/wallet.jpg'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Top-Up',
        title: 'Top Up E-Wallet',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Completed',
    },
    {
        id: 10,
        image: require('../../assets/imgs/BigGardenSalad.png'),
        date: 'Dec 15,2024 | 16:00 PM',
        Price: '$21.40',
        status: 'Orders',
        title: 'Big Garden Salad',
        comletedTitle :'Zero Zero Noodles',
        cancelledTitle:'Bite Me SandWiches',
        statusCancel:'Cancelled',
    },
]